version: '3'
services:
  db:
    restart:
      always
    image: mysql:5.7.22
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db-data: