default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: db
  username: root
  password: password
  port: 3306

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test